### ISSUE TITLE
Data not loading

### ISSUE THREAD

**Issue by G-Vishaal** [3fon3fonov/trifon#11] opened 2019-06-14 14:24 UTC
Hi,
I tried to load one of the .vels file via the data 1 button under the RV data window,but no data is loaded and no plot is displayed.What is the issue here?

**Comment by 3fon3fonov** [comment] 2019-06-14 14:33
Do you have an error on the Stdout/stderr tab? post it here so I can help.

**Comment by mzechmeister** [comment] 2019-06-14 15:21
It probably comes back to the request to simplify the installation as in https://github.com/3fon3fonov/trifon/issues/5#issuecomment-501907292.
Rerunning the installation with all the prompts after a git pull becomes a pain.
For now you could exclude your compiled files from distributing.

**Comment by 3fon3fonov** [comment] 2019-06-14 15:57
The bash scripts are only temporary solution. Close to the official release I will make more robust installer. 
But Ok, I will try to work on improving that experience. Meanwhile, G-Vishaal, let us know if that was indeed your problem and if you manage to fix it by invoking again the bash script installer.

**Comment by G-Vishaal** [comment] 2019-06-16 11:34
I'm not able to understand your suggestion.(my knowledge regarding python is minimal,I'm sorry)
This is the stdout i get when i try to load one of the .vels files:
Hi there! Here you can get some more information from the tool's workflow, stdout/strerr, and piped results.
===== 2019.06.16 17:06:23 =====
Traceback (most recent call last):
  File "F:\Germany intern\trifon-master\gui.py", line 1656, in showDialog_RV_input_file
    self.init_fit()            
  File "F:\Germany intern\trifon-master\gui.py", line 1816, in init_fit
    fit.fitting(fileinput=False,outputfiles=[1,1,1], minimize_fortran=minimize_fortran,  fortran_kill=self.dyn_model_to_kill.value(), timeout_sec=self.master_timeout.value(), minimize_loglik=True,amoeba_starts=0, print_stat=False, eps=self.dyn_model_accuracy.value(), dt=self.time_step_model.value(), npoints=self.points_to_draw_model.value(), model_max= self.model_max_range.value(), model_min= self.model_min_range.value())
  File "./lib\RV_mod\__init__.py", line 2690, in fitting
    text,flag=run_command_with_timeout(self.fortran_input(program=program, fileinput=fileinput, filename=filename, outputfiles=outputfiles,amoeba_starts=amoeba_starts,eps=eps,dt=dt, when_to_kill=fortran_kill, npoints=npoints, model_max = model_max, model_min =model_min), timeout_sec, output=True,pipe=(not bool(outputfiles[2]))) # running command generated by the fortran_input function 
  File "./lib/RV_mod\functions.py", line 176, in run_command_with_timeout
    proc = Popen(args, shell=True, preexec_fn=os.setsid, stdout=text, stderr=text)
AttributeError: module 'os' has no attribute 'setsid'

**Comment by 3fon3fonov** [comment] 2019-06-16 12:41
This seems to be a different problem than #6, which fix is simply to re-run the bash script and recompile the 
fortran routines. A quick look on StackOverflow leads to this https://stackoverflow.com/questions/38083168/attributeerror-module-os-has-no-attribute-setsid

I think this thread says it all.

So it is quite obvious  that you are using the standard Windows pyhon installation, which is not tested at all from my side. I will keep this problem in mind, meanwhile I still recommend you to install the Exo-Striker on Windows 10 trough the "Windows Subsystem for Linux". Look again in "README_for_installation". 
1. Install  "Windows Subsystem for Linux" adopting the Ubuntu system.
2. Install an XServer.
3. Install the Striker using the "linux_debian_install.sh" script. 

This way has been tested and it works. It takes 5-10 mins to setup everything.

**Comment by 3fon3fonov** [comment] 2019-06-24 13:12
That issue was resolved with G-Vishaal. It was confirmed that the tool works fine under the  "Windows Subsystem for Linux".

**Closed by 3fon3fonov** 2019-06-24 13:12 UTC
